### PR TITLE
scrollbar

### PR DESCRIPTION
**Pull request by diomed**
## Changes

- What does this change?
- new scrollbar that more ffits the look off the template

### CODE REVIEW

**Comment by ElianCodes** [comment]
This doesn't seem to work in any of my browsers, tried Safari, Chrome and Firefox

**Comment by diomed** [comment]
it should be allrightish now.
i dont know why svg icons wont display. 
i called them exactly as how fonts are called, from that same folder.

**Comment by ElianCodes** [comment]
It's working in Safari and Chrome, but not yet in Firefox. The icons are not yet shown, if you can't get it working, I suggest to remove the icon placeholders too and just have a scrollbar without buttons

Screenshot 2023-11-15 at 13 23 49

**Comment by diomed** [comment]
in firefox it cant work, because firefox has diffferent way of styling scrollbar. since it's not webkit browser based on chromium.
i was hoping you'd check out what's actually wrong with icons. and modify. is it the path or smth'

**Comment by diomed** [comment]
there. now it's allright.

**Comment by ElianCodes** [comment]
Love it! Really cool stuff!

Thanks for adding this @diomed !

**Review by ElianCodes — APPROVED** [review]

**Pull request merged**
