### PR TITLE
Update Twitter/OpenGraph cards to be .png

### PR DESCRIPTION
**Pull request by gwisk**
Twitter no longer supports .svg cards, updated them to be .pngs

## Changes

Updated the files in v1/generate/og directory using the files in https://github.com/ElianCodes/ElianCodes-frontend
Updated the BaseHead.astro directory to reflect the use .png instead of .svg

### CODE REVIEW

**Comment by ElianCodes** [comment]
Seems that something went wrong here:

```
error   [vite]: Rollup failed to resolve import "@resvg/resvg-js" from "/vercel/path0/src/pages/v1/generate/og/[slug].png.ts".
--
02:22:11.437 | This is most likely unintended because it can break your application at runtime.
02:22:11.438 | If you do want to externalize this module explicitly add it to
02:22:11.439 | `build.rollupOptions.external`
02:22:11.441 | Error: [vite]: Rollup failed to resolve import "@resvg/resvg-js" from "/vercel/path0/src/pages/v1/generate/og/[slug].png.ts"
```

**Comment by gwisk** [comment]
Seems when I copied files over, I might not have done so correctly. Just tested w/ npm run dev and the files generate properly. Should work now.

**Comment by ElianCodes** [comment]
@gwisk, no problemo! Take it easy! You're doing great. 

I'll check in the morning if I can debug anything and let you know what went wrong ❤️

**Comment by ElianCodes** [comment]
Seems like you solved it, but just forgot to install re-svg!

**Pull request closed without merging**
